gnodeb:
  controlif:
    ip: "10.10.1.4"
    port: 9487
  dataif:
    ip: "10.10.1.4"
    port: 2152
  plmnlist:
    mcc: "999"
    mnc: "70"
    tac: "000001"
    gnbid: "000008"
  slicesupportlist:
    sst: "01"
    # sd: "000001" # optional, can be removed if not used
ue:
  msin: "0000000000"
  key: "00000000000000000000000000000000"
  opc: "E8ED289DEBA952E4283B54E88E6183CA"
  amf: "8000"
  sqn: "00000000"
  dnn: "internet"
  routingindicator: "0000"
  hplmn:
    mcc: "999"
    mnc: "70"
  snssai:
    sst: 01
    # sd: "000001" # optional, can be removed if not used
  integrity:
    nia0: false
    nia1: false
    nia2: true
    nia3: false
  ciphering:
    nea0: true
    nea1: false
    nea2: true
    nea3: false
amfif:
  - ip: "10.10.1.2"
    port: 38412
logs:
  level: 4